services:
  - type: web
    name: booking-api
    env: docker
    plan: free

      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_USERNAME
        fromDatabase:
          name: booking-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: booking-db
          property: password
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: booking-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SPRING_DATA_REDIS_URL
        fromService:
          type: redis
          name: booking-redis
          property: connectionString

  - type: redis
    name: booking-redis
    plan: free
    ipAllowList: [] # Allow internal access only

databases:
  - name: booking-db
    plan: free
    databaseName: booking
    user: booking_user
