spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Use Flyway for schema management
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Caching Configuration (Redis - Sidecar)
  data:
    redis:
      host: localhost
      port: 6379

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
      port: 8000 # Access dashboard at http://localhost:8000
    jobs:
      default-number-of-retries: 3
    database:
      skip-create: false
      type: sql

logging:
  level:
    com.example.booking: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dyvxf3gxr}
  api-key: ${CLOUDINARY_API_KEY:938314148915175}
  api-secret: ${CLOUDINARY_API_SECRET:dwXDSi0kcExzVzFkwmbbqRZK9Ys}
  folder: hotel-booking
